# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Moviepick' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moviepick
    pod 'VegaScrollFlowLayout'
    pod 'R.swift'
    pod 'IBAnalyzer'
    pod 'SwiftLint'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Kingfisher'
    pod 'Cosmos', '~> 17.0'

  target 'MoviepickTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviepickUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
